version: "3.8"
services:
  web:
    build: ./app
    image: 262074632670.dkr.ecr.us-west-2.amazonaws.com/django_docker_aws:django_docker_aws_web
    expose:
      - 8000
  nginx:
    build: ./nginx
    image: 262074632670.dkr.ecr.us-west-2.amazonaws.com/django_docker_aws:django_docker_aws_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:


